#exemplo 4
spring:
  application:
    name: greeting-service

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG

#propertie específica da aplicação
greeting-service:
  greeting: "Hello"
  default-value: "My github world"

#propertie para exposição das informações da aplicação pelo actuator
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
