# exemplo3
spring:
  application:
    name: microservice
  #exemplo4
  profiles:
    active:
      - native #busca local
  cloud:
    config:
#      import:
#        - optional:configserver:http://localhost:8888/
      server:
        git:
          uri: https://github.com/raphaelgava/microservices
          #se fosse um repositório privado
#          username:
#          password:
          default-label: main #para pegar a branch padrão ("master")
          search-paths:
            - 'resources/config*'

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect #depreciado
        dialect: org.hibernate.dialect.MySQLDialect # Em teoria, esse é o default
    show-sql: true
    open-in-view: false # https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG

#exemplo 4
#propertie específica da aplicação
greeting-service:
  greeting: "Olá"
  default-value: "Meu mundo"

#propertie para exposição das informações da aplicação pelo actuator
management:
  endpoints:
      web:
          exposure:
              include:
                - '*'

#propertie do cloud server -> para funcionar os exemplos 1, 2, 3 e o Greeting do 4 tem que estar comentado
server:
  port: 8888


#Representa﷿﷿o em properties
#spring.application.name = microservice
#spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
#spring.datasource.url = jdbc:mysql://localhost:3306/rest_with_spring_boot?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC
#spring.datasource.username = root
#spring.datasource.password = admin123
#
#spring.jpa.generate-ddl = true
#spring.jpa.hibernate.ddl-auto = update
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
#spring.jpa.show-sql = true
#
#logging.level.org.hibernate.SQL = DEBUG
